dependencies:

  - name: kube-state-metrics
    version: 2.6.*
    repository: https://mesosphere.github.io/charts/stable/
    condition: kubeStateMetrics.enabled

  - name: prometheus-node-exporter
    version: 1.8.*
    repository: https://mesosphere.github.io/charts/stable/
    condition: nodeExporter.enabled

  - name: grafana
    version: 4.3.*
    repository: https://mesosphere.github.io/charts/stable/
    condition: grafana.enabled
